/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTrackingNumberRouteImport } from './routes/track.$trackingNumber'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminPackagesIndexRouteImport } from './routes/_authenticated/admin.packages.index'
import { Route as AuthenticatedAdminPackagesNewRouteImport } from './routes/_authenticated/admin.packages.new'
import { Route as AuthenticatedAdminPackagesIdIndexRouteImport } from './routes/_authenticated/admin.packages.$id.index'
import { Route as AuthenticatedAdminPackagesIdReceiptRouteImport } from './routes/_authenticated/admin.packages.$id.receipt'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackingNumberRoute = TrackTrackingNumberRouteImport.update({
  id: '/track/$trackingNumber',
  path: '/track/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesIndexRoute =
  AuthenticatedAdminPackagesIndexRouteImport.update({
    id: '/packages/',
    path: '/packages/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesNewRoute =
  AuthenticatedAdminPackagesNewRouteImport.update({
    id: '/packages/new',
    path: '/packages/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesIdIndexRoute =
  AuthenticatedAdminPackagesIdIndexRouteImport.update({
    id: '/packages/$id/',
    path: '/packages/$id/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesIdReceiptRoute =
  AuthenticatedAdminPackagesIdReceiptRouteImport.update({
    id: '/packages/$id/receipt',
    path: '/packages/$id/receipt',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/packages/$id/receipt': typeof AuthenticatedAdminPackagesIdReceiptRoute
  '/admin/packages/$id/': typeof AuthenticatedAdminPackagesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesIndexRoute
  '/admin/packages/$id/receipt': typeof AuthenticatedAdminPackagesIdReceiptRoute
  '/admin/packages/$id': typeof AuthenticatedAdminPackagesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/track/$trackingNumber': typeof TrackTrackingNumberRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/packages/new': typeof AuthenticatedAdminPackagesNewRoute
  '/_authenticated/admin/packages/': typeof AuthenticatedAdminPackagesIndexRoute
  '/_authenticated/admin/packages/$id/receipt': typeof AuthenticatedAdminPackagesIdReceiptRoute
  '/_authenticated/admin/packages/$id/': typeof AuthenticatedAdminPackagesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/track/$trackingNumber'
    | '/admin/customers'
    | '/admin/'
    | '/admin/packages/new'
    | '/admin/packages/'
    | '/admin/packages/$id/receipt'
    | '/admin/packages/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/track/$trackingNumber'
    | '/admin/customers'
    | '/admin'
    | '/admin/packages/new'
    | '/admin/packages'
    | '/admin/packages/$id/receipt'
    | '/admin/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/track/$trackingNumber'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/packages/new'
    | '/_authenticated/admin/packages/'
    | '/_authenticated/admin/packages/$id/receipt'
    | '/_authenticated/admin/packages/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrackTrackingNumberRoute: typeof TrackTrackingNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackingNumber': {
      id: '/track/$trackingNumber'
      path: '/track/$trackingNumber'
      fullPath: '/track/$trackingNumber'
      preLoaderRoute: typeof TrackTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/': {
      id: '/_authenticated/admin/packages/'
      path: '/packages'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/new': {
      id: '/_authenticated/admin/packages/new'
      path: '/packages/new'
      fullPath: '/admin/packages/new'
      preLoaderRoute: typeof AuthenticatedAdminPackagesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/$id/': {
      id: '/_authenticated/admin/packages/$id/'
      path: '/packages/$id'
      fullPath: '/admin/packages/$id/'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages/$id/receipt': {
      id: '/_authenticated/admin/packages/$id/receipt'
      path: '/packages/$id/receipt'
      fullPath: '/admin/packages/$id/receipt'
      preLoaderRoute: typeof AuthenticatedAdminPackagesIdReceiptRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPackagesNewRoute: typeof AuthenticatedAdminPackagesNewRoute
  AuthenticatedAdminPackagesIndexRoute: typeof AuthenticatedAdminPackagesIndexRoute
  AuthenticatedAdminPackagesIdReceiptRoute: typeof AuthenticatedAdminPackagesIdReceiptRoute
  AuthenticatedAdminPackagesIdIndexRoute: typeof AuthenticatedAdminPackagesIdIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPackagesNewRoute: AuthenticatedAdminPackagesNewRoute,
  AuthenticatedAdminPackagesIndexRoute: AuthenticatedAdminPackagesIndexRoute,
  AuthenticatedAdminPackagesIdReceiptRoute:
    AuthenticatedAdminPackagesIdReceiptRoute,
  AuthenticatedAdminPackagesIdIndexRoute:
    AuthenticatedAdminPackagesIdIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrackTrackingNumberRoute: TrackTrackingNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
